# Generated by Django 4.2.27 on 2026-01-07 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 20, 48, 6, 783631, tzinfo=datetime.timezone.utc)),
        ),
    ]
