# Generated by Django 4.2.27 on 2026-01-07 21:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_url_alter_auctionlisting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 21, 33, 3, 65959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
