# Generated by Django 4.2.27 on 2026-01-09 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 10, 15, 53, 581228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Wacthlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='auctions.auctionlisting')),
            ],
        ),
    ]
