# Generated by Django 4.2.27 on 2026-01-09 10:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_end_time_wacthlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 10, 31, 59, 545247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Wacthlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
