# Generated by Django 4.2.27 on 2026-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookfinanz', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='no_name', max_length=10),
        ),
    ]
